#!/usr/bin/env bash
start-services

echo "Creating database..."
sudo -u postgres createuser -DRS root && \
sudo -u postgres createdb -O root gvmd && \
sudo -u postgres psql gvmd -c 'create role dba with superuser noinherit;' && \
sudo -u postgres psql gvmd -c 'grant dba to root;' && \
sudo -u postgres psql gvmd -c 'create extension "uuid-ossp";'
echo "Database created."

echo "Creating certificates..."
gvm-manage-certs -a
echo "Certificates created."

echo "Creating user..."
gvmd --create-user=admin
gvmd --user=admin --new-password=admin
echo "User created."

echo "Creating scanner..."
gvmd --create-scanner="Scanner" --scanner-type="OpenVas" --scanner-host=/run/ospd.sock
echo "Scanner created."

start-openvas

# There is a problem with SCAP Sync: https://github.com/greenbone/gvmd/issues/822
echo "Checking synchronization progress..."
sleep 5
X="$(ps -aux | grep -v grep | grep 'gvmd: Syncing CERT\|gmvd: Reloading')"
while  [ "${#X}" != 0 ]; do
    sleep 1
    X="$(ps -aux | grep -v grep | grep 'gvmd: Syncing CERT\|gmvd: Reloading')"
done
echo "Synchronized update."