#!/usr/bin/env bash
start-services

echo "Creating database..."
sudo -u postgres createuser -DRS root && \
sudo -u postgres createdb -O root gvmd && \
sudo -u postgres psql gvmd -c 'create role dba with superuser noinherit;' && \
sudo -u postgres psql gvmd -c 'grant dba to root;' && \
sudo -u postgres psql gvmd -c 'create extension "uuid-ossp";'
echo "Database created."

echo "Creating certificates..."
gvm-manage-certs -a
echo "Certificates created."

echo "Creating user..."
gvmd --create-user=admin
gvmd --user=admin --new-password=admin
echo "User created."

echo "Creating scanner..."
gvmd --create-scanner="Scanner" --scanner-type="OpenVas" --scanner-host=/run/ospd.sock
echo "Scanner created."

start-openvas