#!/bin/bash
start-services
start-openvas

echo "Synchronizing NVT cache..."
sleep 1
X="$(ps -aux | grep -v grep | grep 'gmvd: Reloading')"
while  [ "${#X}" != 0 ]; do
    sleep 1
    X="$(ps -aux | grep -v grep | grep 'gmvd: Reloading')"
done
sleep 1
echo "NVT cache synchronized."