#!/bin/bash
start-services
start-ospd
start-gvmd

echo "Synchronizing NVT cache..."
sleep 3
X="$(ps -aux | grep -v grep | grep 'openvas: Reloaded')"
while  [ "${#X}" != 0 ]; do
    echo "Still synchronizing NVT cache..."
    sleep 15
    X="$(ps -aux | grep -v grep | grep 'openvas: Reloaded')"
done
echo "NVT cache synchronized."