#!/usr/bin/env bash
echo "Starting OSPD..."
rm -f /var/run/ospd/ospd.pid /var/run/ospd/ospd.sock
ospd-openvas -l /usr/local/var/log/gvm/ospd.log &
echo "OSPD ready."

echo "Pushing plugins to Redis..."
sleep 5
X="$(ps -aux | grep -v grep | grep 'openvas: Reloaded')"
while  [ "${#X}" != 0 ]; do
    sleep 1
    X="$(ps -aux | grep -v grep | grep 'openvas: Reloaded')"
done
echo "Plugins pushed to Redis."

echo "Waiting for OSPD socket..."
sleep 5
while [ ! -e /var/run/ospd/ospd.sock ]; do
  sleep 1
done
echo "OSPD socket ready."

echo "Starting GVMD..."
gvmd --listen-group=service --listen-owner=service --osp-vt-update=/var/run/ospd/ospd.sock
echo "Testing GVMD status..."
sleep 5
X="$(ps -aux | grep -v grep | grep 'gvmd: Waiting')"
while  [ "${#X}" == 0 ]; do
    sleep 1
    X="$(ps -aux | grep -v grep | grep 'gvmd: Waiting')"
done
echo "GVMD ready."

echo "Synchronizing CERT, SCAP and NVT cache..."
sleep 30
X="$(ps -aux | grep -v grep | grep 'gvmd: Syncing CERT\|gvmd: Syncing SCAP\|gvmd: Reloading NVTs')"
while  [ "${#X}" != 0 ]; do
    sleep 1
    X="$(ps -aux | grep -v grep | grep 'gvmd: Syncing CERT\|gvmd: Syncing SCAP\|gvmd: Reloading NVTs')"
done
echo "CERT, SCAP and NVT cache synchronized."