#!/bin/bash
echo "Starting Redis server..."
redis-server /etc/redis/redis.conf

echo "Testing redis status..."
X="$(redis-cli ping)"
while  [ "${X}" != "PONG" ]
do
  echo "Redis not yet ready..."
  sleep 1
  X="$(redis-cli ping)"
done
echo "Redis ready."

echo "Starting PostgreSQL..."
/etc/init.d/postgresql start
echo "PostgreSQL ready."

echo "Rebuilding NVT cache..."
openvas -u
echo "NVT cache ready."

echo "Starting GVMD..."
gvmd --listen-group=service --listen-owner=service
echo "Testing GVMD status..."
sleep 1
X="$(ps | grep gvmd)"
while  [ "${#X}" == 0 ]; do
        echo "GVMD not yet ready..."
        gvmd --listen-group=service --listen-owner=service
        sleep 1
        X="$(ps | grep gvmd)"
done
echo "GVMD ready."