#!/usr/bin/env bash
echo "Starting OSPD..."
rm -f /run/ospd.pid /run/ospd.sock
ospd-openvas -l /usr/local/var/log/gvm/ospd.log --unix-socket /run/ospd.sock --pid-file=/run/ospd.pid &
echo "OSPD ready."

echo "Starting GVMD..."
gvmd --listen-group=service --listen-owner=service --osp-vt-update=/run/ospd.sock
echo "Testing GVMD status..."
sleep 5
X="$(ps -aux | grep -v grep | grep 'gvmd: Waiting')"
while  [ "${#X}" == 0 ]; do
    sleep 1
    X="$(ps -aux | grep -v grep | grep 'gvmd: Waiting')"
done
echo "GVMD ready."

echo "Pushing plugins to Redis..."
sleep 5
X="$(ps -aux | grep -v grep | grep 'openvas: Reloaded')"
while  [ "${#X}" != 0 ]; do
    sleep 1
    X="$(ps -aux | grep -v grep | grep 'openvas: Reloaded')"
done
echo "Plugins pushed to Redis."

echo "Waiting for OSPD socket..."
sleep 5
while [ ! -e /run/ospd.sock ]; do
  sleep 1
done
echo "OSPD socket ready."

# There is a problem with SCAP Sync: https://github.com/greenbone/gvmd/issues/822
echo "Synchronizing certs and NVT cache..."
sleep 60
X="$(ps -aux | grep -v grep | grep 'gvmd: Syncing CERT\|gvmd: Reloading NVTs')"
while  [ "${#X}" != 0 ]; do
    sleep 1
    X="$(ps -aux | grep -v grep | grep 'gvmd: Syncing CERT\|gvmd: Reloading NVTs')"
done
echo "Certs and NVT cache synchronized."