#!/usr/bin/env bash
echo "Starting GVMD..."
gvmd --listen-group=service --listen-owner=service --osp-vt-update=/run/ospd.sock
echo "Testing GVMD status..."
sleep 3
X="$(ps -aux | grep -v grep | grep 'gvmd: Waiting')"
while  [ "${#X}" == 0 ]; do
    echo "GVMD not yet ready..."
    sleep 3
    X="$(ps -aux | grep -v grep | grep 'gvmd: Waiting')"
done
echo "GVMD ready."