#!/bin/bash
echo "Starting Redis server..."
redis-server /etc/redis/redis.conf

echo "Testing redis status..."
X="$(redis-cli ping)"
while  [ "${X}" != "PONG" ]
do
  echo "Redis not yet ready..."
  sleep 1
  X="$(redis-cli ping)"
done
echo "Redis ready."

echo "Starting PostgreSQL..."
/etc/init.d/postgresql start
echo "PostgreSQL ready."

echo "Starting OpenVAS Scanner..."
ldconfig && openvas
sleep 2
X="$(ps aufx | grep openvas | grep -v 'grep')"
while  [ "${#X}" == 0 ]; do
        echo "OpenVAS Scanner not yet ready..."
        ldconfig && openvas
        sleep 2
        X="$(ps aufx | grep openvas | grep -v 'grep')"
done
echo "OpenVAS Scanner ready."

echo "Starting GVMD..."
ldconfig && gvmd
echo "Testing GVMD status..."
sleep 1
X="$(ps | grep gvmd)"
while  [ "${#X}" == 0 ]; do
        echo "GVMD not yet ready..."
        ldconfig && gvmd
        sleep 1
        X="$(ps | grep gvmd)"
done
echo "GVMD ready."
