#!/bin/bash
start-services
start-ospd

echo "Starting GVMD..."
gvmd --listen-group=service --listen-owner=service --osp-vt-update=/run/ospd.sock
echo "Testing GVMD status..."
sleep 3
X="$(ps -aux | grep '[g]vmd: Waiting')"
while  [ "${#X}" == 0 ]; do
    echo "GVMD not yet ready..."
    sleep 3
    X="$(ps -aux | grep '[g]vmd: Waiting')"
done
sleep 3
echo "GVMD ready."