#!/bin/bash
echo "Disabling THP..."
echo never > /sys/kernel/mm/transparent_hugepage/enabled
echo never > /sys/kernel/mm/transparent_hugepage/defrag
sleep 1
echo "THP disabled."

echo "Starting Redis server..."
redis-server /etc/redis/redis.conf
echo "Testing Redis status..."
sleep 1
X="$(redis-cli ping)"
while  [ "${X}" != "PONG" ]
do
  sleep 1
  X="$(redis-cli ping)"
done
echo "Redis ready."

echo "Starting PostgreSQL..."
/etc/init.d/postgresql start
echo "Testing PostgreSQL status..."
sleep 1
X="$(ps -aux | grep -v grep | grep 'postgres: 11/main: startup')"
while  [ "${#X}" != 0 ]; do
  sleep 1
  X="$(ps -aux | grep -v grep | grep 'postgres: 11/main: startup')"
done
echo "PostgreSQL ready."