#!/bin/bash
greenbone-certdata-sync > /dev/null 2>&1 &

echo "Syncing CERTS feed..."
sleep 30
while [ -e /usr/local/var/run/feed-update.lock ]; do
  echo "Syncing CERTS feed in progress..."
  sleep 30
done