#!/bin/bash
echo "Starting Redis server..."
redis-server /etc/redis/redis.conf

echo "Testing redis status..."
X="$(redis-cli ping)"
while  [ "${X}" != "PONG" ]
do
  echo "Redis not yet ready..."
  sleep 1
  X="$(redis-cli ping)"
done
echo "Redis ready."

echo "Starting PostgreSQL..."
/etc/init.d/postgresql start
echo "PostgreSQL ready."

echo "Syncing OpenVAS feeds..."
greenbone-nvt-sync
greenbone-scapdata-sync
greenbone-certdata-sync
echo "OpenVAS feeds synced."

echo "Starting OSPD..."
ospd-openvas -l /usr/local/var/log/gvm/ospd.log --unix-socket /run/ospd.sock --pid-file=/run/ospd.pid &
echo "OSPD ready."

echo "Starting GVMD..."
gvmd --listen-group=service --listen-owner=service --osp-vt-update=/run/ospd.sock
echo "Testing GVMD status..."
sleep 1
X="$(ps -aux | grep gvmd)"
while  [ "${#X}" == 0 ]; do
        echo "GVMD is not ready yet..."
        sleep 1
        X="$(ps -aux | grep gvmd)"
done
sleep 15
X="$(ps -aux | grep '[g]vmd: Syncing')"
while  [ "${#X}" != 0 ]; do
        echo "GVMD is still syncing update..."
        sleep 15
        X="$(ps -aux | grep '[g]vmd: Syncing')"
done
echo "GVMD ready."