#!/bin/bash
start-services

echo "Syncing OpenVAS feeds..."
greenbone-nvt-sync
greenbone-scapdata-sync
greenbone-certdata-sync
echo "OpenVAS feeds synced."

start-ospd

echo "Starting GVMD..."
gvmd --listen-group=service --listen-owner=service --osp-vt-update=/run/ospd.sock
echo "Testing GVMD status..."
sleep 3
X="$(ps -aux | grep '[g]vmd: Waiting')"
while  [ "${#X}" == 0 ]; do
    echo "GVMD not yet ready..."
    sleep 3
    X="$(ps -aux | grep '[g]vmd: Waiting')"
done
sleep 3
X="$(ps -aux | grep '[g]vmd: Syncing')"
while  [ "${#X}" != 0 ]; do
    echo "GVMD is still syncing update..."
    sleep 15
    X="$(ps -aux | grep '[g]vmd: Syncing')"
done
echo "GVMD ready."