#!/bin/bash
start-services

echo "Syncing OpenVAS feeds..."
greenbone-nvt-sync
#Problem with long SCAP sync: https://github.com/greenbone/gvmd/issues/822
sleep 10
greenbone-scapdata-sync
sleep 10
greenbone-certdata-sync
echo "OpenVAS feeds synced."

start-openvas